"""
src/ui/strings.py
Full UI string dictionary for all 8 supported languages.
Add a new language by adding a new top-level key here — no other file needs changing.
"""

UI_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "flag": "🇬🇧", "name": "English",
        "tagline": "Multilingual BERT Mental Health Risk Prediction & Vision Analysis",
        "caption": "Mysore University · AI&DS · Enterprise Architecture V2.0",
        "status_bert": "BERT Model Ready",
        "status_vision": "Vision API Ready",
        "status_vision_off": "Vision API Offline",
        "tab_text": "📝 Text Analysis",
        "tab_image": "🖼️ Image Analysis",
        "tab_batch": "⚡ Batch Analysis",
        "input_label": "Enter your thoughts or describe how you feel:",
        "input_placeholder": "Type or paste text in English here...",
        "btn_analyze": "🔍 Analyze Now",
        "spinner_translate": "Translating securely offline...",
        "spinner_bert": "Running BERT inference...",
        "result_title": "Diagnosis Result",
        "confidence_title": "Confidence Breakdown",
        "disclaimer": "⚠️ Research prototype only. NOT a clinical tool. Always consult a qualified professional.",
        "img_upload": "Upload image (JPG, PNG, WEBP, BMP):",
        "btn_vision": "🔬 Analyze Image",
        "spinner_vision": "Analyzing via Groq Vision...",
        "batch_label": "Paste multiple entries (one per line):",
        "batch_placeholder": "Post 1 (English)\nPost 2 (any Indian language)\nPost 3...",
        "btn_batch": "⚡ Run Batch Analysis",
        "batch_summary": "Batch Summary",
        "total": "Total Records",
        "depression": "Depression Risk",
        "anxiety": "Anxiety Risk",
        "normal": "Normal",
        "download_csv": "⬇️ Download CSV",
        "download_txt": "⬇️ Download Report",
        "advice_normal": "No significant risk indicators detected. Maintain your healthy routine.",
        "advice_anxiety": "Anxiety patterns detected. Consider speaking with a mental health professional.",
        "advice_depression": "Depression patterns detected. Please reach out to a mental health professional.",
        "choose_lang": "Choose your language",
        "model_info": "Fine-tuned BERT · bert-base-uncased · Reddit Mental Health Dataset",
        "offline_badge": "🔒 Offline Translation",
        "warn_long_input": "⚠️ Long input ({words} words). BERT works best under {max} words — tail may be truncated.",
        "err_translation": "❌ Translation failed: {error}. Cannot analyze untranslated text.",
        "history_title": "📋 Recent Results",
        "history_empty": "No results yet. Run an analysis to see history here.",
    },
    "hi": {
        "flag": "🇮🇳", "name": "हिन्दी",
        "tagline": "बहुभाषी BERT मानसिक स्वास्थ्य जोखिम विश्लेषण",
        "caption": "मैसूर विश्वविद्यालय · AI&DS · एंटरप्राइज V2.0",
        "status_bert": "BERT मॉडल तैयार है",
        "status_vision": "विज़न API तैयार है",
        "status_vision_off": "विज़न API उपलब्ध नहीं",
        "tab_text": "📝 पाठ विश्लेषण",
        "tab_image": "🖼️ छवि विश्लेषण",
        "tab_batch": "⚡ बैच विश्लेषण",
        "input_label": "अपने विचार लिखें या अपनी भावना बताएं:",
        "input_placeholder": "यहाँ हिन्दी में टेक्स्ट टाइप करें...",
        "btn_analyze": "🔍 अभी विश्लेषण करें",
        "spinner_translate": "ऑफलाइन अनुवाद हो रहा है...",
        "spinner_bert": "BERT विश्लेषण चल रहा है...",
        "result_title": "निदान परिणाम",
        "confidence_title": "विश्वास स्तर",
        "disclaimer": "⚠️ शोध प्रोटोटाइप केवल। नैदानिक उपकरण नहीं। हमेशा किसी पेशेवर से परामर्श लें।",
        "img_upload": "छवि अपलोड करें (JPG, PNG, WEBP, BMP):",
        "btn_vision": "🔬 छवि विश्लेषण करें",
        "spinner_vision": "Groq Vision के माध्यम से विश्लेषण...",
        "batch_label": "एकाधिक प्रविष्टियाँ पेस्ट करें (प्रति पंक्ति एक):",
        "batch_placeholder": "पंक्ति 1 (हिन्दी)\nLine 2 (English)\nLínea 3...",
        "btn_batch": "⚡ बैच विश्लेषण चलाएं",
        "batch_summary": "बैच सारांश",
        "total": "कुल रिकॉर्ड",
        "depression": "अवसाद जोखिम",
        "anxiety": "चिंता जोखिम",
        "normal": "सामान्य",
        "download_csv": "⬇️ CSV डाउनलोड करें",
        "download_txt": "⬇️ रिपोर्ट डाउनलोड करें",
        "advice_normal": "कोई महत्वपूर्ण जोखिम नहीं मिला। अपनी स्वस्थ दिनचर्या बनाए रखें।",
        "advice_anxiety": "चिंता के संकेत मिले। किसी मानसिक स्वास्थ्य विशेषज्ञ से बात करें।",
        "advice_depression": "अवसाद के संकेत मिले। कृपया किसी मानसिक स्वास्थ्य विशेषज्ञ से संपर्क करें।",
        "choose_lang": "भाषा चुनें",
        "model_info": "Fine-tuned BERT · Reddit मानसिक स्वास्थ्य डेटासेट",
        "offline_badge": "🔒 ऑफलाइन अनुवाद",
        "warn_long_input": "⚠️ लंबा इनपुट ({words} शब्द)। BERT {max} शब्दों में सर्वश्रेष्ठ काम करता है।",
        "err_translation": "❌ अनुवाद विफल: {error}. अनुवाद के बिना विश्लेषण संभव नहीं।",
        "history_title": "📋 हाल के परिणाम",
        "history_empty": "अभी तक कोई परिणाम नहीं। विश्लेषण चलाएं।",
    },
    "kn": {
        "flag": "🇮🇳", "name": "ಕನ್ನಡ",
        "tagline": "ಬಹುಭಾಷಾ BERT ಮಾನಸಿಕ ಆರೋಗ್ಯ ಅಪಾಯ ವಿಶ್ಲೇಷಣೆ",
        "caption": "ಮೈಸೂರು ವಿಶ್ವವಿದ್ಯಾಲಯ · AI&DS · ಎಂಟರ್‌ಪ್ರೈಸ್ V2.0",
        "status_bert": "BERT ಮಾದರಿ ಸಿದ್ಧವಾಗಿದೆ",
        "status_vision": "ವಿಷನ್ API ಸಿದ್ಧ",
        "status_vision_off": "ವಿಷನ್ API ಆಫ್‌ಲೈನ್",
        "tab_text": "📝 ಪಠ್ಯ ವಿಶ್ಲೇಷಣೆ",
        "tab_image": "🖼️ ಚಿತ್ರ ವಿಶ್ಲೇಷಣೆ",
        "tab_batch": "⚡ ಬ್ಯಾಚ್ ವಿಶ್ಲೇಷಣೆ",
        "input_label": "ನಿಮ್ಮ ಆಲೋಚನೆಗಳನ್ನು ಅಥವಾ ಭಾವನೆಯನ್ನು ನಮೂದಿಸಿ:",
        "input_placeholder": "ಇಲ್ಲಿ ಕನ್ನಡದಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...",
        "btn_analyze": "🔍 ಈಗ ವಿಶ್ಲೇಷಿಸಿ",
        "spinner_translate": "ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಅನುವಾದ ಮಾಡಲಾಗುತ್ತಿದೆ...",
        "spinner_bert": "BERT ವಿಶ್ಲೇಷಣೆ ನಡೆಯುತ್ತಿದೆ...",
        "result_title": "ನಿದಾನ ಫಲಿತಾಂಶ",
        "confidence_title": "ವಿಶ್ವಾಸ ಮಟ್ಟ",
        "disclaimer": "⚠️ ಸಂಶೋಧನಾ ಮಾದರಿ ಮಾತ್ರ. ವೈದ್ಯಕೀಯ ಸಾಧನವಲ್ಲ. ಯಾವಾಗಲೂ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
        "img_upload": "ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ (JPG, PNG, WEBP, BMP):",
        "btn_vision": "🔬 ಚಿತ್ರ ವಿಶ್ಲೇಷಿಸಿ",
        "spinner_vision": "Groq Vision ಮೂಲಕ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
        "batch_label": "ಬಹು ನಮೂದುಗಳನ್ನು ಅಂಟಿಸಿ (ಪ್ರತಿ ಸಾಲು ಒಂದು):",
        "batch_placeholder": "ಸಾಲು 1 (ಕನ್ನಡ)\nLine 2 (English)\nसाल 3 (Hindi)...",
        "btn_batch": "⚡ ಬ್ಯಾಚ್ ವಿಶ್ಲೇಷಣೆ ಚಲಾಯಿಸಿ",
        "batch_summary": "ಬ್ಯಾಚ್ ಸಾರಾಂಶ",
        "total": "ಒಟ್ಟು ದಾಖಲೆಗಳು",
        "depression": "ಖಿನ್ನತೆ ಅಪಾಯ",
        "anxiety": "ಆತಂಕ ಅಪಾಯ",
        "normal": "ಸಾಮಾನ್ಯ",
        "download_csv": "⬇️ CSV ಡೌನ್‌ಲೋಡ್",
        "download_txt": "⬇️ ವರದಿ ಡೌನ್‌ಲೋಡ್",
        "advice_normal": "ಯಾವುದೇ ಗಮನಾರ್ಹ ಅಪಾಯ ಕಂಡುಬಂದಿಲ್ಲ. ಆರೋಗ್ಯಕರ ಜೀವನಶೈಲಿ ಮುಂದುವರಿಸಿ.",
        "advice_anxiety": "ಆತಂಕದ ಚಿಹ್ನೆಗಳು ಕಂಡುಬಂದಿವೆ. ಮಾನಸಿಕ ಆರೋಗ್ಯ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
        "advice_depression": "ಖಿನ್ನತೆಯ ಚಿಹ್ನೆಗಳು ಕಂಡುಬಂದಿವೆ. ದಯವಿಟ್ಟು ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
        "choose_lang": "ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ",
        "model_info": "Fine-tuned BERT · Reddit ಮಾನಸಿಕ ಆರೋಗ್ಯ ಡೇಟಾಸೆಟ್",
        "offline_badge": "🔒 ಆಫ್‌ಲೈನ್ ಅನುವಾದ",
        "warn_long_input": "⚠️ ದೀರ್ಘ ಇನ್‌ಪುಟ್ ({words} ಪದಗಳು). BERT {max} ಪದಗಳಲ್ಲಿ ಉತ್ತಮವಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ.",
        "err_translation": "❌ ಅನುವಾದ ವಿಫಲ: {error}.",
        "history_title": "📋 ಇತ್ತೀಚಿನ ಫಲಿತಾಂಶಗಳು",
        "history_empty": "ಇನ್ನೂ ಫಲಿತಾಂಶಗಳಿಲ್ಲ.",
    },
    "ta": {
        "flag": "🇮🇳", "name": "தமிழ்",
        "tagline": "பன்மொழி BERT மன நல ஆபத்து பகுப்பாய்வு",
        "caption": "மைசூர் பல்கலைக்கழகம் · AI&DS · Enterprise V2.0",
        "status_bert": "BERT மாதிரி தயார்",
        "status_vision": "Vision API தயார்",
        "status_vision_off": "Vision API இல்லை",
        "tab_text": "📝 உரை பகுப்பாய்வு",
        "tab_image": "🖼️ படம் பகுப்பாய்வு",
        "tab_batch": "⚡ தொகுதி பகுப்பாய்வு",
        "input_label": "உங்கள் எண்ணங்களை அல்லது உணர்வுகளை உள்ளிடவும்:",
        "input_placeholder": "இங்கே தமிழில் தட்டச்சு செய்யுங்கள்...",
        "btn_analyze": "🔍 இப்போது பகுப்பாய்வு செய்",
        "spinner_translate": "ஆஃப்லைனில் மொழிபெயர்க்கப்படுகிறது...",
        "spinner_bert": "BERT பகுப்பாய்வு இயங்குகிறது...",
        "result_title": "நோயறிதல் முடிவு",
        "confidence_title": "நம்பிக்கை அளவு",
        "disclaimer": "⚠️ ஆராய்ச்சி முன்மாதிரி மட்டும். மருத்துவ கருவி அல்ல.",
        "img_upload": "படத்தை பதிவேற்றவும் (JPG, PNG, WEBP, BMP):",
        "btn_vision": "🔬 படத்தை பகுப்பாய்வு செய்",
        "spinner_vision": "Groq Vision மூலம் பகுப்பாய்வு...",
        "batch_label": "பல உள்ளீடுகளை ஒட்டவும் (வரிக்கு ஒன்று):",
        "batch_placeholder": "வரி 1 (தமிழ்)\nLine 2 (English)\nसाल 3...",
        "btn_batch": "⚡ தொகுதி பகுப்பாய்வை இயக்கு",
        "batch_summary": "தொகுதி சுருக்கம்",
        "total": "மொத்த பதிவுகள்",
        "depression": "மனச்சோர்வு ஆபத்து",
        "anxiety": "பதற்றம் ஆபத்து",
        "normal": "சாதாரண",
        "download_csv": "⬇️ CSV பதிவிறக்கம்",
        "download_txt": "⬇️ அறிக்கை பதிவிறக்கம்",
        "advice_normal": "குறிப்பிடத்தக்க ஆபத்து இல்லை. ஆரோக்கியமான வாழ்க்கையை தொடரவும்.",
        "advice_anxiety": "பதற்ற அறிகுறிகள் உள்ளன. மன நல நிபுணரிடம் பேசவும்.",
        "advice_depression": "மனச்சோர்வு அறிகுறிகள் உள்ளன. மன நல நிபுணரை தொடர்பு கொள்ளவும்.",
        "choose_lang": "மொழி தேர்ந்தெடுக்கவும்",
        "model_info": "Fine-tuned BERT · Reddit மன நல Dataset",
        "offline_badge": "🔒 ஆஃப்லைன் மொழிபெயர்ப்பு",
        "warn_long_input": "⚠️ நீண்ட உள்ளீடு ({words} வார்த்தைகள்). BERT {max} வார்த்தைகளில் சிறப்பாக செயல்படுகிறது.",
        "err_translation": "❌ மொழிபெயர்ப்பு தோல்வி: {error}.",
        "history_title": "📋 சமீபத்திய முடிவுகள்",
        "history_empty": "இன்னும் முடிவுகள் இல்லை.",
    },
    "te": {
        "flag": "🇮🇳", "name": "తెలుగు",
        "tagline": "బహుభాషా BERT మానసిక ఆరోగ్య ప్రమాద విశ్లేషణ",
        "caption": "మైసూరు విశ్వవిద్యాలయం · AI&DS · Enterprise V2.0",
        "status_bert": "BERT మోడల్ సిద్ధంగా ఉంది",
        "status_vision": "Vision API సిద్ధం",
        "status_vision_off": "Vision API అందుబాటులో లేదు",
        "tab_text": "📝 వచన విశ్లేషణ",
        "tab_image": "🖼️ చిత్ర విశ్లేషణ",
        "tab_batch": "⚡ బ్యాచ్ విశ్లేషణ",
        "input_label": "మీ ఆలోచనలు లేదా భావాలు నమోదు చేయండి:",
        "input_placeholder": "ఇక్కడ తెలుగులో టైప్ చేయండి...",
        "btn_analyze": "🔍 ఇప్పుడు విశ్లేషించండి",
        "spinner_translate": "ఆఫ్‌లైన్‌లో అనువదిస్తున్నారు...",
        "spinner_bert": "BERT విశ్లేషణ జరుగుతోంది...",
        "result_title": "నిర్ధారణ ఫలితం",
        "confidence_title": "విశ్వాస స్థాయి",
        "disclaimer": "⚠️ పరిశోధన నమూనా మాత్రమే. వైద్య సాధనం కాదు.",
        "img_upload": "చిత్రం అప్‌లోడ్ చేయండి (JPG, PNG, WEBP, BMP):",
        "btn_vision": "🔬 చిత్రాన్ని విశ్లేషించండి",
        "spinner_vision": "Groq Vision ద్వారా విశ్లేషిస్తున్నారు...",
        "batch_label": "బహుళ ఎంట్రీలను అతికించండి (ప్రతి పంక్తి ఒకటి):",
        "batch_placeholder": "పంక్తి 1 (తెలుగు)\nLine 2 (English)...",
        "btn_batch": "⚡ బ్యాచ్ విశ్లేషణ అమలు చేయండి",
        "batch_summary": "బ్యాచ్ సారాంశం",
        "total": "మొత్తం రికార్డులు",
        "depression": "నిరాశ ప్రమాదం",
        "anxiety": "ఆందోళన ప్రమాదం",
        "normal": "సాధారణం",
        "download_csv": "⬇️ CSV డౌన్‌లోడ్",
        "download_txt": "⬇️ నివేదిక డౌన్‌లోడ్",
        "advice_normal": "గణనీయమైన ప్రమాదం కనుగొనబడలేదు. ఆరోగ్యకరమైన జీవితాన్ని కొనసాగించండి.",
        "advice_anxiety": "ఆందోళన సంకేతాలు కనుగొనబడ్డాయి. మానసిక ఆరోగ్య నిపుణుడితో మాట్లాడండి.",
        "advice_depression": "నిరాశ సంకేతాలు కనుగొనబడ్డాయి. మానసిక ఆరోగ్య నిపుణుడిని సంప్రదించండి.",
        "choose_lang": "భాషను ఎంచుకోండి",
        "model_info": "Fine-tuned BERT · Reddit Mental Health Dataset",
        "offline_badge": "🔒 ఆఫ్‌లైన్ అనువాదం",
        "warn_long_input": "⚠️ పొడవైన ఇన్‌పుట్ ({words} పదాలు). BERT {max} పదాలలో ఉత్తమంగా పనిచేస్తుంది.",
        "err_translation": "❌ అనువాదం విఫలమైంది: {error}.",
        "history_title": "📋 ఇటీవలి ఫలితాలు",
        "history_empty": "ఇంకా ఫలితాలు లేవు.",
    },
    "ml": {
        "flag": "🇮🇳", "name": "മലയാളം",
        "tagline": "ബഹുഭാഷാ BERT മാനസിക ആരോഗ്യ അപകട വിശകലനം",
        "caption": "മൈസൂർ സർവ്വകലാശാല · AI&DS · Enterprise V2.0",
        "status_bert": "BERT മോഡൽ തയ്യാർ",
        "status_vision": "Vision API തയ്യാർ",
        "status_vision_off": "Vision API ലഭ്യമല്ല",
        "tab_text": "📝 ടെക്സ്റ്റ് വിശകലനം",
        "tab_image": "🖼️ ചിത്ര വിശകലനം",
        "tab_batch": "⚡ ബാച്ച് വിശകലനം",
        "input_label": "നിങ്ങളുടെ ചിന്തകൾ അല്ലെങ്കിൽ വികാരങ്ങൾ നൽകുക:",
        "input_placeholder": "ഇവിടെ മലയാളത്തിൽ ടൈപ്പ് ചെയ്യൂ...",
        "btn_analyze": "🔍 ഇപ്പോൾ വിശകലനം ചെയ്യൂ",
        "spinner_translate": "ഓഫ്‌ലൈൻ പരിഭാഷ...",
        "spinner_bert": "BERT വിശകലനം നടക്കുന്നു...",
        "result_title": "നിർണ്ണയ ഫലം",
        "confidence_title": "വിശ്വസ്തത നില",
        "disclaimer": "⚠️ ഗവേഷണ മാതൃക മാത്രം. വൈദ്യശാസ്ത്ര ഉപകരണമല്ല.",
        "img_upload": "ചിത്രം അപ്‌ലോഡ് ചെയ്യൂ (JPG, PNG, WEBP, BMP):",
        "btn_vision": "🔬 ചിത്രം വിശകലനം ചെയ്യൂ",
        "spinner_vision": "Groq Vision വഴി വിശകലനം...",
        "batch_label": "ഒന്നിലധികം എൻട്രികൾ ഒട്ടിക്കൂ (ഓരോ വരിയും ഒന്ന്):",
        "batch_placeholder": "വരി 1 (മലയാളം)\nLine 2 (English)...",
        "btn_batch": "⚡ ബാച്ച് വിശകലനം പ്രവർത്തിപ്പിക്കൂ",
        "batch_summary": "ബാച്ച് സംഗ്രഹം",
        "total": "ആകെ രേഖകൾ",
        "depression": "വിഷാദ അപകടം",
        "anxiety": "ഉത്കണ്ഠ അപകടം",
        "normal": "സാധാരണ",
        "download_csv": "⬇️ CSV ഡൗൺലോഡ്",
        "download_txt": "⬇️ റിപ്പോർട്ട് ഡൗൺലോഡ്",
        "advice_normal": "കാര്യമായ അപകടം കണ്ടെത്തിയില്ല. ആരോഗ്യകരമായ ജീവിതം തുടരൂ.",
        "advice_anxiety": "ഉത്കണ്ഠ ലക്ഷണങ്ങൾ കണ്ടെത്തി. ഒരു മാനസിക ആരോഗ്യ വിദഗ്ദ്ധനോട് സംസാരിക്കൂ.",
        "advice_depression": "വിഷാദ ലക്ഷണങ്ങൾ കണ്ടെത്തി. ദയവായി ഒരു വിദഗ്ദ്ധനെ സമീപിക്കൂ.",
        "choose_lang": "ഭാഷ തിരഞ്ഞെടുക്കൂ",
        "model_info": "Fine-tuned BERT · Reddit Mental Health Dataset",
        "offline_badge": "🔒 ഓഫ്‌ലൈൻ പരിഭാഷ",
        "warn_long_input": "⚠️ നീണ്ട ഇൻപുട്ട് ({words} വാക്കുകൾ). BERT {max} വാക്കുകളിൽ മികച്ചതാണ്.",
        "err_translation": "❌ പരിഭാഷ പരാജയപ്പെട്ടു: {error}.",
        "history_title": "📋 സമീപകാല ഫലങ്ങൾ",
        "history_empty": "ഇനിയും ഫലങ്ങൾ ഇല്ല.",
    },
    "bn": {
        "flag": "🇮🇳", "name": "বাংলা",
        "tagline": "বহুভাষিক BERT মানসিক স্বাস্থ্য ঝুঁকি বিশ্লেষণ",
        "caption": "মহীশূর বিশ্ববিদ্যালয় · AI&DS · Enterprise V2.0",
        "status_bert": "BERT মডেল প্রস্তুত",
        "status_vision": "Vision API প্রস্তুত",
        "status_vision_off": "Vision API অনুপলব্ধ",
        "tab_text": "📝 পাঠ্য বিশ্লেষণ",
        "tab_image": "🖼️ ছবি বিশ্লেষণ",
        "tab_batch": "⚡ ব্যাচ বিশ্লেষণ",
        "input_label": "আপনার চিন্তা বা অনুভূতি লিখুন:",
        "input_placeholder": "এখানে বাংলায় টাইপ করুন...",
        "btn_analyze": "🔍 এখন বিশ্লেষণ করুন",
        "spinner_translate": "অফলাইনে অনুবাদ হচ্ছে...",
        "spinner_bert": "BERT বিশ্লেষণ চলছে...",
        "result_title": "রোগ নির্ণয় ফলাফল",
        "confidence_title": "আস্থার মাত্রা",
        "disclaimer": "⚠️ গবেষণা প্রোটোটাইপ শুধু। চিকিৎসা সরঞ্জাম নয়।",
        "img_upload": "ছবি আপলোড করুন (JPG, PNG, WEBP, BMP):",
        "btn_vision": "🔬 ছবি বিশ্লেষণ করুন",
        "spinner_vision": "Groq Vision এর মাধ্যমে বিশ্লেষণ...",
        "batch_label": "একাধিক এন্ট্রি পেস্ট করুন (প্রতি লাইনে একটি):",
        "batch_placeholder": "লাইন ১ (বাংলা)\nLine 2 (English)...",
        "btn_batch": "⚡ ব্যাচ বিশ্লেষণ চালান",
        "batch_summary": "ব্যাচ সারসংক্ষেপ",
        "total": "মোট রেকর্ড",
        "depression": "বিষণ্নতা ঝুঁকি",
        "anxiety": "উদ্বেগ ঝুঁকি",
        "normal": "স্বাভাবিক",
        "download_csv": "⬇️ CSV ডাউনলোড",
        "download_txt": "⬇️ রিপোর্ট ডাউনলোড",
        "advice_normal": "কোনো উল্লেখযোগ্য ঝুঁকি পাওয়া যায়নি। সুস্থ জীবনযাপন অব্যাহত রাখুন।",
        "advice_anxiety": "উদ্বেগের লক্ষণ পাওয়া গেছে। মানসিক স্বাস্থ্য বিশেষজ্ঞের সাথে কথা বলুন।",
        "advice_depression": "বিষণ্নতার লক্ষণ পাওয়া গেছে। দয়া করে একজন বিশেষজ্ঞের সাথে যোগাযোগ করুন।",
        "choose_lang": "ভাষা বেছে নিন",
        "model_info": "Fine-tuned BERT · Reddit Mental Health Dataset",
        "offline_badge": "🔒 অফলাইন অনুবাদ",
        "warn_long_input": "⚠️ দীর্ঘ ইনপুট ({words} শব্দ)। BERT {max} শব্দে সেরা কাজ করে।",
        "err_translation": "❌ অনুবাদ ব্যর্থ: {error}.",
        "history_title": "📋 সাম্প্রতিক ফলাফল",
        "history_empty": "এখনও ফলাফল নেই।",
    },
    "mr": {
        "flag": "🇮🇳", "name": "मराठी",
        "tagline": "बहुभाषिक BERT मानसिक आरोग्य जोखीम विश्लेषण",
        "caption": "म्हैसूर विद्यापीठ · AI&DS · Enterprise V2.0",
        "status_bert": "BERT मॉडेल तयार",
        "status_vision": "Vision API तयार",
        "status_vision_off": "Vision API अनुपलब्ध",
        "tab_text": "📝 मजकूर विश्लेषण",
        "tab_image": "🖼️ प्रतिमा विश्लेषण",
        "tab_batch": "⚡ बॅच विश्लेषण",
        "input_label": "आपले विचार किंवा भावना नमूद करा:",
        "input_placeholder": "येथे मराठीत टाइप करा...",
        "btn_analyze": "🔍 आता विश्लेषण करा",
        "spinner_translate": "ऑफलाइन भाषांतर होत आहे...",
        "spinner_bert": "BERT विश्लेषण चालू आहे...",
        "result_title": "निदान निकाल",
        "confidence_title": "विश्वास पातळी",
        "disclaimer": "⚠️ फक्त संशोधन प्रोटोटाइप. वैद्यकीय साधन नाही.",
        "img_upload": "प्रतिमा अपलोड करा (JPG, PNG, WEBP, BMP):",
        "btn_vision": "🔬 प्रतिमा विश्लेषण करा",
        "spinner_vision": "Groq Vision द्वारे विश्लेषण...",
        "batch_label": "एकाधिक नोंदी पेस्ट करा (प्रति ओळ एक):",
        "batch_placeholder": "ओळ 1 (मराठी)\nLine 2 (English)...",
        "btn_batch": "⚡ बॅच विश्लेषण चालवा",
        "batch_summary": "बॅच सारांश",
        "total": "एकूण नोंदी",
        "depression": "नैराश्य धोका",
        "anxiety": "चिंता धोका",
        "normal": "सामान्य",
        "download_csv": "⬇️ CSV डाउनलोड",
        "download_txt": "⬇️ अहवाल डाउनलोड",
        "advice_normal": "कोणताही महत्त्वपूर्ण धोका आढळला नाही. निरोगी जीवनशैली सुरू ठेवा.",
        "advice_anxiety": "चिंतेची चिन्हे आढळली. मानसिक आरोग्य तज्ञाशी बोला.",
        "advice_depression": "नैराश्याची चिन्हे आढळली. कृपया तज्ञाशी संपर्क साधा.",
        "choose_lang": "भाषा निवडा",
        "model_info": "Fine-tuned BERT · Reddit Mental Health Dataset",
        "offline_badge": "🔒 ऑफलाइन भाषांतर",
        "warn_long_input": "⚠️ दीर्घ इनपुट ({words} शब्द). BERT {max} शब्दांमध्ये सर्वोत्तम काम करते.",
        "err_translation": "❌ भाषांतर अयशस्वी: {error}.",
        "history_title": "📋 अलीकडील निकाल",
        "history_empty": "अद्याप निकाल नाहीत.",
    },
}

# Language selection options (code → display info)
LANG_OPTIONS: dict[str, dict[str, str]] = {
    "en": {"label": "English",   "emoji": "EN", "native": "English"},
    "hi": {"label": "Hindi",     "emoji": "HI", "native": "हिन्दी"},
    "kn": {"label": "Kannada",   "emoji": "KN", "native": "ಕನ್ನಡ"},
    "ta": {"label": "Tamil",     "emoji": "TA", "native": "தமிழ்"},
    "te": {"label": "Telugu",    "emoji": "TE", "native": "తెలుగు"},
    "ml": {"label": "Malayalam", "emoji": "ML", "native": "മലയാളം"},
    "bn": {"label": "Bengali",   "emoji": "BN", "native": "বাংলা"},
    "mr": {"label": "Marathi",   "emoji": "MR", "native": "मराठी"},
}
